[Unit]
Wants=network-online.target
After=network-online.target
StartLimitIntervalSec=0

[Service]
ExecStartPre=
ExecStartPre=/bin/sh -c 'until /usr/sbin/ip -4 addr show | /usr/bin/grep -q "inet 10\.10\.10\.1/"; do /bin/sleep 1; done'
ExecStartPre=/usr/sbin/nginx -t -q -g 'daemon on; master_process on;'
Restart=on-failure
RestartSec=5
TimeoutStartSec=180
