[local]
localhost ansible_connection=local

[builders_linux_amd64_cuda]
daedalus-01 ansible_host=10.10.10.20

[builders_linux_amd64_cuda:vars]
ansible_user=ai-forge
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
